
title: Jingyi F. / Joe F.  # Add a space after the period

logo: 1.jpg # Use a relative path to logo image 

description: AI (Machine Learning) and Data science in Speech/Audio Processing - Doing real research for a better world. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

# google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: feng.jingyi@g.sp.m.is.nagoya-u.ac.jp # Allow visitors to contact you
