
title: J. Feng  # Add a space after the period

logo: fotor-20240928201544.png # Use a relative path to logo image 

description: AI and ML in Speech Processing # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

# google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console
google_analytics: G-KXT9Z048H4

email: feng.jingyi@g.sp.m.is.nagoya-u.ac.jp # Allow visitors to contact you

# <!--
# iiynjgef/iiynjgef is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
# You can click the Preview link to take a look at your changes.

# page reference: https://github.com/Allan-gitrepos/My_resume
# -->
