
title: Jingyi F. / Joe F.  # Add a space after the period

logo: pic1.png # Use a relative path to logo image 

description: AI (Machine Learning) and Data Science in Speech/Audio Processing # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

# google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: feng.jingyi@g.sp.m.is.nagoya-u.ac.jp # Allow visitors to contact you

# <!--
# iiynjgef/iiynjgef is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
# You can click the Preview link to take a look at your changes.

# page reference: https://github.com/Allan-gitrepos/My_resume
# -->
